baseURL = "https://yourdomain.com/"
languageCode = "it-it"
title = "Contrada San Giorgio - Desio"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Sito ufficiale della contrada San Giorgio di Desio."
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]